//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BdOfResume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducation
    {
        public int Id { get; set; }
        public Nullable<int> IdEmp { get; set; }
        public Nullable<int> IdEduc { get; set; }
        public Nullable<int> UniverId { get; set; }
        public Nullable<int> SpecialityId { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual University University { get; set; }
    }
}
