//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BdOfResume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpSkills
    {
        public int Id { get; set; }
        public Nullable<int> IdEmp { get; set; }
        public Nullable<int> IdSkill { get; set; }
        public string Comment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
