//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BdOfResume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTask
    {
        public int Id { get; set; }
        public int IdParticipation { get; set; }
        public int IdTask { get; set; }
    
        public virtual Participation Participation { get; set; }
        public virtual Task Task { get; set; }
    }
}
