//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BdOfResume.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Project : ICatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Participation = new HashSet<Participation>();
        }
    
        public int Id { get; set; }
        [Required]
        [Display(Name = "Название проекта")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Область проекта")]
        public string Area { get; set; }
        [Required]
        [Display(Name = "Дата начала проекта")]
        public Nullable<System.DateTime> DateBegin { get; set; }
        [Display(Name = "Дата окончания проекта")]
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participation> Participation { get; set; }
    }
}
