// <auto-generated />
namespace BdOfResume.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Loma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Loma));
        
        string IMigrationMetadata.Id
        {
            get { return "201906240327060_Loma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
